Add Java to the list of backends
aserto-demo/todo-application pull request #8
Opened 2023-08-25 14:52 UTC by BogdanIrimie

2023-08-25 15:23 UTC, apoland approved these changes

2023-08-27 22:41 UTC, ogazitt requested changes

2023-08-27 22:41 UTC, ogazitt commented on README.md
> +| <img src="https://raw.githubusercontent.com/aserto-dev/_aserto_-docs/main/static/dotnet-core.svg" height="30" /> | .NET | https://github.com/aserto-demo/todo-dotnet-v2  |
the image src url for dotnet-core was mangled as part of this PR.

2023-08-27 22:44 UTC, ogazitt commented on README.md
> +| <img src="https://raw.githubusercontent.com/aserto-dev/_aserto_-docs/main/static/dotnet-core.svg" height="30" /> | .NET | https://github.com/aserto-demo/todo-dotnet-v2  |
Plus, "Go" appears twice.

2023-08-27 22:46 UTC, ogazitt approved these changes

2023-08-27 22:50 UTC, merged